# Generated by Django 4.2.14 on 2024-07-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_order_value_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
